export let maiores_gastos = {
    'columns': [
      'dates',
      'orgao',
      'uasg',
      'ds_fundamento_legal',
      'ds_justificativa',
      'ds_objeto_licitacao',
      'no_cargo_resp_decl_disp',
      'no_responsavel_decl_disp',
      'vr_estimado'
    ],
    'data': [
      [
        '2005-08-01',
        'COMANDO DO EXERCITO',
        'HOSPITAL MILITAR DE AREA DE PORTO ALEGRE',
        'Fundamento Legal: Artigo 25  ,  Caput  , da Lei 8.666\/93',
        'Justificativa: Competicao e inviavel, uma vez que se admite credenciar todas OCS que  atendam necessidades da UG-FuSEx contratante.',
        'Objeto: Prestacao de servico de diagnistico por ',
        'Ordenador de Despesas do HGePA',
        'GILMAR CORREA DE FIGUEIREDO',
        18000000000.0
      ],
      [
        '2014-05-16',
        'COMANDO DA AERONAUTICA',
        'MAER-GAPBR-GRUPAMENTO DE APOIO DE BRASILIA\/DF',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Conforme Ata de Acordo no004\/DCTA-COPAC\/2014, de 25\/04\/2014, o valor contratado foi considerado aceitavel pela administraca',
        'Objeto: Aquisicao de materiais e prestacao de s ervicos para a producao e o fornecimento de 28 aeronaves KC-390 ',
        'Ordenador de Despesas Copac',
        'JOSE AUGUSTO CREPALDI AFFONSO',
        7255869086.0
      ],
      [
        '2016-11-18',
        'COMANDO DO EXERCITO',
        'COMANDO LOGISTICO',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Inviabilidade de competicao',
        'Objeto: Aquisicao de viatura blindada Guarani ',
        'Ordenador de Despesas Substituto',
        'MARCELO MORAES RODRIGUES',
        5939679681.0
      ],
      [
        '2009-12-15',
        'COMANDO DO EXERCITO',
        'ESTADO-MAIOR DO EXERCITO-MEX\/DF',
        'Fundamento Legal: Artigo 25, inciso I, da Lei  8.666\/93',
        'Justificativa: I- A empresa e produtora exclusiva, em razao de estar desenvolvendo um protitipo e lote piloto.',
        'ao do Exercito Brasileiro, em conformidade com especificacies e composicies de Lotes anuais a serem definidos por intermedio de Termos Aditiv os. Objeto: Servico de fabricacao em serie no pais e fornecimento de 2044 (dois mil e quarenta e quatro) VIATURAS BLINDADAS DE TRANSPORTE DE PES SOAL M>>DIA DE RODAS (VBTP-MR), apis Ato de Adoc ',
        'Ordenador de Despesas do EME',
        'CARLOS ALBERTO PASSARELLA ARANTES - CEL',
        5443227413.0
      ],
      [
        '2016-01-04',
        'UNIVERSIDADE FEDERAL DO PARA',
        'HOSPITAL UNIVERSITARIO BETINA FERRO E SOUZA',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Fornecimento de PROTESE PARA IMPLANTE COCLEAR que atendam as necessidades dos Pacientes Oriundos do SUS.',
        'Objeto: Fornecimento de PROTESE PARA IMPLANTE C OCLEAR (abaixo descritos), aos usuarios do SUS de acordo com a indicacao tecnica do Hospital U niversitario Bettina Ferro de Souza, cujos prec os referentes PS prestacao de servicos, nos term os do artigo 26 da Lei. no. 8.080\/90 serao aque les constantes da Tabela SIA\/SUS do Ministerio da Saode - PORTARIAS No 1.278, DE 20 DE OUTUBRO  DE 1999 - GM\/MS E PORTARIA No 337, DE 6 DE ABR IL DE 2015 - GM\/MS. Obs.: Continuacao no Edital  1.1 do OBJETO. ',
        'Coordenador Administrativo',
        'CELIO D ALBUQUERQUE NEVES FILHO',
        5259618000.0
      ],
      [
        '2015-11-27',
        'INST.FED.DE EDUC.,CIENC.E TEC.DO RJ',
        'INST.FED.DE EDUC.,CIENC.E TEC.DO R.DE JANEIRO',
        'Fundamento Legal: Art. 25o, Inciso II e art. 13o, inc. VI da mesma Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Servicos tecnicos de notiria especializacao',
        'Objeto: Execucao de acies de qualificacao profi ssional para o segmento turismo com foco na oli mpada e paraolimpada Rio 2016. ',
        'Ordenador de Despesas',
        'PAULO ROBERTO DE ASSIS PASSOS',
        4525000000.0
      ],
      [
        '2009-04-07',
        'COMANDO DA AERONAUTICA',
        'MAER-GAPBR-GRUPAMENTO DE APOIO DE BRASILIA\/DF',
        'Fundamento Legal: Artigo 25, Caput, da Lei     8.666\/93',
        'Justificativa: Analisado pelo GAC-EMBRAER conforme relatirios 001, 004 e 006\/GAC-EMBRAER\/09-C',
        'Objeto: Fornecimento de 02 (dois) protitipos da  aeronave de transporte militar e reabastecimen to (Aeronave KC-X), incluindo a prestacao de se rvicos para o gerenciamento da producao e monta gem das aeronaves, entrega da documentacao do p rojeto, relatirios de desenvolvimento e certifi cacao, relatirios de voos de teste e de avaliac ao operacional e um pacote de dados de produto. ',
        'Ordenador de Despesas',
        'MAJ BRIG AR DIRCEU TONDOLO NuRO',
        3028104951.0
      ],
      [
        '2009-04-07',
        'COMANDO DA AERONAUTICA',
        'MAER-GAPBR-GRUPAMENTO DE APOIO DE BRASILIA\/DF',
        'Fundamento Legal: Artigo 25, Caput, da Lei     8.666\/93',
        'Justificativa: O preco foi analisado pela SDDP-COPAC, por intermedio do Grupo de Acompanhamen-to e Controle(GAC-EMBRAER).',
        'Objeto: Fornecimento de 02 (dois) protitipos da aeronave de transporte militar e reabastecimen- to (Aeronave KC-X), incluindo a prestacao    de servicos para o gerenciamento da producao     e montagem das anvs, entrega da documentacao   do projeto, relatirios de desenvolvimento e certi- ficacao, relatirios de voos de teste e de  ava- liacao operacional e um pacote de dados de pro- duto. ',
        'Presidente da COPAC',
        'MAJ BRIG AR DIRCEU TONDOLO NoRO',
        3028104951.0
      ],
      [
        '2009-04-07',
        'COMANDO DA AERONAUTICA',
        'MAER-GAPBR-GRUPAMENTO DE APOIO DE BRASILIA\/DF',
        'Fundamento Legal: Artigo 25, Caput, da Lei     8.666\/93',
        'Justificativa: O preco foi analizado pela SDDP-COPAC, por intermedio do Grupo de Acompanhamento e Controle(GAC-EMBRAER).',
        'Objeto: Fornecimento de 02 (dois) protitipos da  aeronave de transporte militar e reabastecimen to (Aeronave KC-X), incluindo a prestacao    de  servicos para o gerenciamento da producao    e  montagem das Aeronaves, entrega da   documenta cao do projeto, relatirios de desenvolvimento e  certificacao, relatirios de voos de teste e de  avaliacao operacional e um pacote de dados  de  produto. ',
        'Presidente da COPAC',
        'MAJ BRIG AR DIRCEU TONDOLO NoRO',
        3028104951.0
      ],
      [
        '2016-12-01',
        'MINISTERIO DA FAZENDA',
        'SUPERINTENDENCIA DE ADMINISTRACAO DO MF - PR',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Por se tratar de empresa sem concorrancia.',
        'Objeto: Prestacao de Servico Poblico de forneci mento de energia eletrica, de estrutura tarifar ia horaria verde, subgrupo AS. ',
        'Gerente da DivisY=o de Recursos Logisticos',
        'REGINA MARIA LOVATO DE OLIVEIRA',
        2516394670.0
      ],
      [
        '2016-11-25',
        'COMANDO DA MARINHA',
        'CENTRO DE OBTENCAO DA MARINHA\/RJ',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: A Empresa Companhia Brasileira de Cartuchos e exclusiva  para fornecimento do objeto em lide',
        'Objeto: Aquisicao de municao ',
        'Ordenador de Despesas',
        'RICARDO YUKIO IAMAGUCHI',
        1890170000.0
      ],
      [
        '2017-09-21',
        'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCACAO',
        'FNDE-MEC-FUNDO NAC.DE DESENV.DA EDUACACAO\/DF',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Objeto: Prestacao dos servicos de recebimento e \/ou coleta, transporte, tratamento, distribuica o e entrega domiciliaria urbana, em !mbito naci onal, de encomendas relativas aos Programas do Livro. ',
        'Ordenador de Despesas',
        'JOSE FERNANDO UCHOA COSTA NETO',
        1659666294.0
      ],
      [
        '2012-12-06',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Dispensa prevista na Lei no 8.666\/93.',
        'Objeto: Contratacao da Empresa de Tecnologia da  Informacao da Previdancia Social - DATAPREV, p ara prestacao de servicos especializados em hos ting e colocation, suporte e manutencao de sist emas com uso de tecnologia da informacao. ',
        'Diretor de OrSSamento, FinanSSas e Logstica',
        'PEDRO AUGUSTO SANGUINETTI FERREIRA',
        1591803686.0
      ],
      [
        '2017-11-22',
        'MINISTERIO DA FAZENDA',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao do Serpro, empresa integrante da Administracao Poblica Indireta, para prestacao de servicos de TI',
        'Objeto: Prestacao, contnua e initerrupta, de s ervicos de producao de solucies de tecnologia d a informacao, desenvolvimento, manutencao de si stemas, modelagem de solucies de tecnologia da informacao, suporte e sustentacao referentes ao s processos da Secretaria da Receita Federal do  Brasil. ',
        'Coordenador-geral de ProgramaSSY=o e Logstica Substituto',
        'FABIO COIMBRA MIRANDA',
        1560332213.0
      ],
      [
        '2018-11-21',
        'MINISTERIO DA FAZENDA',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Prestacao de servicos de informatica por entidade da Administracao Poblica, criada para esse fim especfico.',
        'Objeto: Prestacao contnua e ininterrupta de se rvicos de Tecnologia da Informacao, relativos PS  producao de solucies de TI, desenvolvimento e manutencao de sistemas, modelagem de solucies d e TI e suporte e sustentacao referentes aos pro cessos estrategicos da Secretaria da Receita Fe deral do Brasil. ',
        'Coordenador-geral de ProgramaSSY=o e Logstica',
        'MARCOS ANTONIO DA CUNHA',
        1549003735.0
      ],
      [
        '2017-11-30',
        'MINISTERIO DA FAZENDA',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Empresa integrante da Administracao Poblica Indireta, prestadora de servicos de TI',
        'Objeto: Servicos de producao de solucies de TI,  desenvolvimento e manutencao de sistemas, mode lagem de solucies de TI, suporte e sustentacao referente aos processos estrategicos da RFB. ',
        'Coordenador-geral de ProgramaSSY=o e Logstica Substituto',
        'FABIO COIMBRA MIRANDA',
        1525996145.0
      ],
      [
        '2012-08-23',
        'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCACAO',
        'FNDE-MEC-FUNDO NAC.DE DESENV.DA EDUACACAO\/DF',
        'Fundamento Legal: Art. 24o, Inciso VIII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Art. 24o, Inciso VIII da Lei no 8.666 de 21\/06\/1993.',
        'Objeto: Prestacao dos servicos de recebimento e \/ou coleta, transporte, distribuicao e comprova cao das entregas, em !mbito nacional, de encome ndas relativas aos Programas do Livro. ',
        'Ordenador de Despesas',
        'RAFAEL PEREIRA TORINO',
        1510648028.0
      ],
      [
        '2010-02-02',
        'COMANDO DA AERONAUTICA',
        'BASE AEREA DO RECIFE',
        'Fundamento Legal: Artigo 24, inciso XXII, da   Lei 8.666\/93',
        'Justificativa: Companhia concessionaria para   distribuicao de energia eletrica no Estado de  Pernambuco,conforme Dec. de 22 de marco de 2000',
        'Objeto: Fornecimento de energia eletrica ',
        'Ordenador de Despesas',
        'JOAO MAURICIO MARQUES MAGALHAES CEL AV',
        1500000000.0
      ],
      [
        '2016-04-29',
        'MINISTERIO DO DESENV. SOCIAL E COMBATE A FOME',
        'SECRETARIA NACIONAL DE RENDA E CIDADANIA',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Em razao do estabelecido no artigo 12 da Lei no 10.836, de 09 de janeiro de 2004.',
        'Objeto: Contratacao da CAIXA ECONoMICA FEDERAL (CAIXA) para a operacionalizacao do Cadastro thn ico e das acies de transferancia de renda no !m bito do Ministerio do Desenvolvimento Social e Combate PS Fome (MDS). ',
        'Secretario Nacional',
        'TIAGO FALCAO SILVA',
        1162002495.0
      ],
      [
        '2012-12-28',
        'MINISTERIO DA FAZENDA',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Servicos prestados pelo SERPRO, empresa integrante da administracao poblica federal.',
        'Objeto: Prestacao em regime de empreitada por p reco unitario de servicos de Tecnologia da Info rmacao - TI, compreendendo processamento de dad os,administracao de redes locais e de longa dis t!ncia, manutencao e desenvolvimento de sistema s de informacao e outros servicos de informatic a, para atendimento a todas as areas da Receita  Federal do Brasil, com fundamento no art. 2o d a Lei no 5.615, de 13 de outubro de 1970, alter ada pela Lei no 12.249, de 11 de junho de 2010. ',
        'Coordenador-geral de ProgramaSSY=o e Logstica Substituto',
        'RODRIGO OCTAVIO MACIEL',
        1152684678.0
      ],
      [
        '2018-12-28',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXIV da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Dispensada licitacao por se tratar de fundacao de apoio a irgao da administracao poblica direta.',
        'Objeto: Vacina Humana Antigripal. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode.',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        968960000.0
      ],
      [
        '2011-04-29',
        'MINISTERIO DA FAZENDA',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Artigo 24, inciso XVI, da    Lei 8.666\/93',
        'Justificativa: Empresa Federal criada para presfim especfico',
        'Objeto: Servico TI ',
        'Coordenadora-Geral da Copol',
        'ANA MARTHA FONSECA DO VALLE',
        949545026.0
      ],
      [
        '2014-02-04',
        'SERVICO FEDERAL DE PROCESSAMENTO DE DADOS',
        'SERPRO - SEDE BRASILIA',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O Convanio de Reciprocidade intenta o cumprimento da Clausula 38 do ACT 2013\/2014.',
        'Objeto: Motua utilizacao da rede de prestadores  de servicos de assitancia medico-hospitalar cr edenciada ',
        'Diretor',
        'ANTONIO JOAO NOCCHI PARERA',
        920354471.0
      ],
      [
        '2018-03-29',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXIV da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Dispensada licitacao por se tratar de fundacao de apoio PS irgao da administracao poblica direta',
        'Objeto: Aquisicao de VACINA HUMANA, ANTIGRIPAL,  AQUOSA, 0,50 ML, INJETuVEL ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        909600000.0
      ],
      [
        '2012-12-20',
        'MINISTERIO DO DESENV. SOCIAL E COMBATE A FOME',
        'SECRETARIA NACIONAL DE RENDA E CIDADANIA',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: A contratada e o agente operador do Programa Bolsa Familia nos termos do art. 12, da Lei n.o 10.836\/2004.',
        'Objeto: Prestacao de servicos objetivando: A op eracionalizacao do Cadastro thnico para Programa s Sociais - Cadastro thnico;a operacionalizacao das acies de transferancia direta de renda do G overno Federal; e a operacionalizacao de acies de transferancia direta de renda dos governos e staduais, municipais ou do Distrito Federal. Pe riodo de vigancia: 30 meses, contados a partir de 01\/01\/2013. ',
        'Secret$?rio Nacional de Renda de Cidadania',
        'LUIS HENRIQUE DA SILVA DE PAIVA',
        901800000.0
      ],
      [
        '2017-03-13',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXIV da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao da Fundacao de Apoio ao Instituto Butantan.',
        'Objeto: Aquisicao de Vacina Humana Antigripal a quosa 0,50mL - Injetavel. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode.',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        864600000.0
      ],
      [
        '2018-10-23',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Por se tratar de Transferancia de Tecnologia de produto estrategico para o SUS',
        'Objeto: Aquisicao de CONCENTRADO DE FATOR DE CO AGULA,PO, FATOR VIII RECOMBINANTE, PO LIOFILO P \/ INJETuVEL ',
        'Coordenadora Geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode Substituta',
        'ADRIANA RODOVALHO BEZERRA',
        864000000.0
      ],
      [
        '2001-01-10',
        'MINISTERIO DA FAZENDA',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Artigo 24 ,inciso XVI ,da Lei8.666\/93',
        'Justificativa: Empresa poblica criada para essefim especfico',
        'Objeto: Prestacao de servicos de tratamento  de informacies, processamento de dados por  inter- medio de computacao eletrenica, manutencao    e desenvolvimento de sistemas e comunicacao    de dados para as areas de atuacao da Secretaria da Receita Federal ',
        'Coordenador-Geral de ProgramaSSY=o e Logstica',
        'JOS>> RIBAMAR MENDES DINIZ',
        844890117.0
      ],
      [
        '2012-10-31',
        'COMANDO DO EXERCITO',
        'BASE ADMINISTRATIVA DO CCOMGEX',
        'Fundamento Legal: Art. 24o, Inciso XXVIII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O envolvimento cumulativo dos aspectos da alta tecnologia e defesa nacional.',
        'Objeto: Servico de implantacao e integracao dos  Subsistemas de Sensoriamento e de Apoio PS Deci sao da fase inicial do Projeto Piloto do SISFRO N. RFR: Processo de Dispensa 001\/2012-ACODE-CCO MGEX.  Detalhamento dos objetos entregaveis. ',
        'Ordenador de Depesas',
        'ROBSON COCINO DA COSTA',
        839664954.0
      ],
      [
        '2012-10-31',
        'COMANDO DO EXERCITO',
        'BASE ADMINISTRATIVA DO CCOMGEX',
        'Fundamento Legal: Art. 24o, Inciso XXVIII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O envolvimento cumulativo dos aspectos da alta complexidade tecnoligica e defesa nacional.',
        'Objeto: Servico de implantacao e integracao dos  Subsistemas de Sensoriamento e de Apoio PS Deci sao da fase inicial do Projeto Piloto do SISFRO N ',
        'Ordenador de Despesas',
        'ROBSON COCINO DA COSTA',
        839664954.0
      ],
      [
        '2008-09-04',
        'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCACAO',
        'FNDE-MEC-FUNDO NAC.DE DESENV.DA EDUACACAO\/DF',
        'Fundamento Legal: Artigo 25, Caput, da Lei     8.666\/93',
        'Justificativa: Artigo 25, Caput, da Lei 8.666\/93',
        'Objeto: Prestacao de servicos relativos ao rece bimento e\/ou coleta, transporte, distribuicao e  comprovacao das entregas, em !mbito nacional, de encomendas relativas aos Programas do Livro. ',
        'Ordenador de Despesas e Presidente do FNDE',
        'DANIEL SILVA BALABAN',
        830748736.0
      ],
      [
        '2016-03-18',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXIV da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao de Fundacao de apoio ao Instituto Butantan.',
        'Objeto: Vacina Humana, antigripal, aquosa, 0,50  ml, injetavel. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para a Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        778680000.0
      ],
      [
        '2008-12-31',
        'RECEITA FEDERAL DO BRASIL',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Artigo 24, inciso XVI, da Lei8.666\/93',
        'Justificativa: SERPRO e integrante da Administracao Poblica, criado para prestar ao Ministerio da os servicos que serao contratados.',
        'Objeto: Prestacao de servicos de tratamento de dados, redes de longa dist!ncia e locais, manut encao e desenvolvimento de sistema de dados, e servicos especiais, por intermedio de computaca o eletrenica para a RFB. ',
        'Coordenador-Geral de ProgramaSSY=o e Logstica',
        'ANToNIO MuRCIO DE OLIVEIRA AGUIAR',
        745670597.0
      ],
      [
        '2010-08-02',
        'DEPARTAMENTO DE POLICIA FEDERAL\/MJ',
        'PRO-AMAZONIA\/PROMOTEC - DPF',
        'Fundamento Legal: Artigo 24, inciso XIV, da    Lei 8.666\/93',
        'Justificativa: Para atender as necessidades da CPLAM\/DLOG\/DPF.a',
        'Objeto: Contratacao da Societe Francaise dexpo rtation de materiels, Systemes et Services Rele vant des Ministeres de i\'interieru - SOFREMI vi sando ao fornecimento e PS implatacao dos sistem as, equipamentos , materiais e servicos que com poem o Projeto Pri- amazonia\/Promotec II. ',
        'Diretor Geral do DPF',
        'LUIZ FERNANDO CORREA',
        721860000.0
      ],
      [
        '2013-05-24',
        'MINISTERIO DO TURISMO',
        'COORDENACAO-GERAL DE RECURSOS LOGISTICOS',
        'Fundamento Legal: Art. 25o, Inciso II da Lei no 8.666 de 21\/06\/1993 combinado com o art. 13o, Inciso IV da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Para atender PSs necessidades do Ministerio do Turismo.',
        'Objeto: Prestacao de servicos pela CONTRATADA, na operacionalizacao de projetos de infraestrut ura turstica apoiados pelo  Programa de Aceler acao do Crescimento   PAC,  enquadrados na Acao   Apoio a Projetos de Infraestrutura Turstica , gerida pela CONTRATANTE, lastreado com recurs os consignados no Orcamento Geral da Uniao, a t tulo de transferancia obrigatiria, na forma do  disposto em instrumentos a serem editados pela  CONTRATANTE. ',
        'Diretor de GestY=o Inerna',
        'RUBENS PORTUGAL BACELLAR',
        697000000.0
      ],
      [
        '2013-05-24',
        'MINISTERIO DO TURISMO',
        'COORDENACAO-GERAL DE RECURSOS LOGISTICOS',
        'Fundamento Legal: Art. 24o, Inciso VIII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Atender as necessidades do MTur',
        'Objeto: Contratacao de empresa para a prestacao  de servicos pela contratada, na operacionaliza cao de projetos de infraestrutura turstica apo iados pelo Programa de Aceleracao do Cresciment o - PAC, enquadrados na Acao  Apoio a Projetos de Infraestrutura Turstica , gerida pelo Contr atante, lastreado com recursos consignados no O rcamento Geral da Uniao, a ttulo de transferan cia obrigatiria, na forma do disposto em instru mentos a serem editados pelo Contratante. ',
        'Diretor de GestY=o Interna',
        'RUBENS PORTUGAL BACELLAR',
        680000000.0
      ],
      [
        '2015-07-23',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: GILEAD SCIENCES FARMAC 1\/4 UTICA DO BRASIL LTDA detem a exclusividade do produto em todo o territirio nacional do medicamento.',
        'Objeto: Aquisicao de 2.684.304 comprimidos de S OFOSBUVIR 400mg. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        678904773.0
      ],
      [
        '2017-12-07',
        'MINISTERIO DA CIENCIA,TECNOLOGIA E INOVACAO',
        'MCT-COORD. GERAL DE RECURSOS LOGISTICOS\/DF',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Inviabilidade de competicao.',
        'Objeto: Contratacao direta da Telecomunicacies Brasileiras S. A.   TELEBRAS para prestar os se rvicos em regime continuado de transmissao bidi recional de dados, em !mbito nacional, para o P rograma Governo Eletrenico   Servico de Atendim ento ao Cidadao - Gesac, por um perodo de 60 ( sessenta) meses. ',
        'Diretor de InclusY=o Digital',
        'AMERICO TRISTAO BERNARDES',
        663575000.0
      ],
      [
        '2014-04-28',
        'COMANDO DA AERONAUTICA',
        'MAER-GAPBR-GRUPAMENTO DE APOIO DE BRASILIA\/DF',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Dotar a Forca Aerea Brasileira com uma aeronave de inspecao em voo com capacidade de homologar os auxlios PS navegacao',
        'Objeto: Aquisicao de 6 aeronaves de Inspecao em  Voo ',
        'Ordenador Despesa Copac',
        'JOSE AUGUSTO CREPALDI AFFONSO',
        662261166.0
      ],
      [
        '2012-04-13',
        'FUNDO DE AMPARO AO TRABALHADOR',
        'COORDENACAO-GERAL DE LOGIST. E ADMINIST.\/MTE',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Em atendimento ao Parecer Conjur no 56\/2012, fls. 151 a 156 dos autos.',
        'Objeto: Contratacao de servicos especializados de Tecnologia da Informacao para atender aos pr ogramas da Secretaria de Polticas Poblicas de Emprego, conforme Projeto Basico fls. 78 a 116, com vigancia de 60 meses. ',
        'Subsecret$?rio de Planejamento, OrSSamento e AdministraSSY=o',
        'ANTONIO FERNANDO DECNOP MARTINS',
        656891708.0
      ],
      [
        '2016-07-07',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao em que ha transferancia de tecnologia de produtos estrategicos no !mbito da Fundacao Ezequiel Dias.',
        'Objeto: Vacina Humana Meningocicica conjugada g rupo C - Solucao Injetavel. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        656550000.0
      ],
      [
        '2015-12-15',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: A empresa Abbvie Farmacautica LTDA detem a exclusividade do produto HUMIRA  em todo territirio nacional.',
        'Objeto: Trata-se de aquisicao de 819.780 sering as de Adalimumabe, 40mg, injetavel ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        636223060.0
      ],
      [
        '2014-11-05',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: A empresa ABBVIE FARMAC 1\/4 UTICA LTDA, detem a exclusividade, em todo o territirio nacional, do medicamento.',
        'Objeto: Aquisicao de 769.746 seringas do medica mento Adalimumabe 40mg,solucao injetavel. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        628836297.0
      ],
      [
        '2016-09-05',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: A empresa ABBVIE FARMAC 1\/4 UTICA  LTDA., detem a exclusividade do produto Humirax, em todo o territirio nacional.',
        'Objeto: Seringas de Adalimumabe 40mg, Solucao I njetavel. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        621880336.0
      ],
      [
        '2018-01-16',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Objeto: Prestacao de servicos estrategicos, com uns e exclusivos de solucao de tecnologia da in formacao (TI), visando atender PSs necessidades do INSS. ',
        'Diretor de OrSSamento FinanSSas e Logstica',
        'JOSE ORLANDO RIBEIRO CARDOSO',
        620632273.0
      ],
      [
        '2018-05-23',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Objeto: Prestacao de servicos estrategicos, com uns e exclusivos de solucao de tecnologia da in formacao (TI), visando atender PSs necessidades do INSS ',
        'Diretora de OrSSamento, FinanSSas e Logstica - Substituta',
        'GILVANEIRE CAVALCANTI BELTRAO',
        620632273.0
      ],
      [
        '2016-01-21',
        'EMPRESAS DE ENERGIA',
        'AMAZONAS GERACAO E TRANSMISSAO DE ENERGIA S.A',
        'Fundamento Legal: Art. 24o, Inciso IV da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Atendimento a Portaria no 15\/2016, de 20\/01\/2016, oriunda do Ministerio de Minas e Energia - MME',
        'Objeto: Prestacao de servicos de locacao de gru pos geradores no montante de 135MW, para o aten dimento a Portaria no 15\/2016, de 20\/01\/2016, o riunda do Ministerio de Minas e Energia - MME ',
        'Diretor de OperaSSY=o',
        'WADY CHARONE JUNIOR',
        611555025.0
      ],
      [
        '2015-03-02',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso VIII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Butantan e uma Instituicao Poblica Estadual, subordinada PS Coord. dos Instit. de Pesq. da Sec.  Est. da Saode de SP.',
        'Objeto: Aquisicao de 54.000.000 doses de VACINA  HUMANA, ANTIGRIPAL, AQUOSA, 0,50 ML, INJETuVEL ; 2.500.000 de doses de VACINA HUMANA, CONTRA R AIVA EM C>>LULAS VERO, DOSE IMUNIZANTE 0,5 ML, P O LIOFILO P\/ INJETuVEL + DILUENTE e 20.500.000 doses de VACINA HUMANA, CONTRA V?RUS DA HEPATIT E B, RECOMBINANTE, 10 MCG\/ML, SUSPENSPO INJETuV EL. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        599795000.0
      ],
      [
        '2018-12-19',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao direta frente PS inviabilidade de competicao do objeto contratado',
        'Objeto: Aquisicao de ADALIMUMABE de 40mg, na ap resentacao de seringa preenchida e frasco-ampol a. ',
        'Coordenador Geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        598724698.0
      ],
      [
        '2013-12-26',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Abbott Laboratirios do Brasil Ltda e fabricante e distribuidora exclusiva, em todo o territirio nacional, do medicamento.',
        'Objeto: Aquisicao de 680.000 seringas preenchid as de Adalimumabe 40mg ',
        'Coordenadora Geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode - Substituta',
        'MICHELLE WERNECK DE OLIVEIRA',
        597978400.0
      ],
      [
        '2016-07-21',
        'INST.NACIONAL DE EST.E PESQUISAS EDUCACIONAIS',
        'MEC\/INEP\/INST.NAC.DE EST.E PESQ.EDUCAC.\/DF',
        'Fundamento Legal: Art. 24o, Inciso XIII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: inciso XIII, art. 24 da lei 8.666\/93.',
        'Objeto: Contratacao do Consircio Cesgranrio-Ceb raspe para prestacao de servicos especializados  de aplicacao para o Exame Nacional do Ensino M edio - ENEM, conforme condicies e especificacie s contidas no Projeto Basico. ',
        'Diretora de GestY=o e Planejamento',
        'EUNICE DE OLIVEIRA FERREIRA SANTOS',
        596860059.0
      ],
      [
        '2018-04-10',
        'MINISTERIO DAS CIDADES',
        'COORDENAcaO GERAL DE RECURSOS LOGISTICOS MCID',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993',
        'Justificativa: Inexigvel a licitacao quando houver a inviabilidade de competicao',
        'Objeto: Contratacao da Caixa Econemica Federal -  CAIXA, que tem por objeto os servicos para g estao operacional de contratos de repasse para execucao de programas geridos pela uniao, lastr eados com recursos consignados no Orcamento-Ger al da uniao para transferancias voluntarias, co nforme regras e diretrizes definidas na Instruc ao Normativa no 2\/2018, do Ministerio do Planej amento Desenvolvimento e Gestao ',
        'Coordenador Geral de Recursos Logsticos',
        'DANIEL FEITOSA BARBOSA',
        592967356.0
      ],
      [
        '2017-11-20',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao direta frente PS inviabilidade de competicao do objeto contratado.',
        'Objeto: Aquisicao de ADALIMUMABE 40MG, SOLU,PO INJETuVEL. ',
        'Coordenador Geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        589987600.0
      ],
      [
        '2007-12-28',
        'RECEITA FEDERAL DO BRASIL',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Artigo 24, inciso XVI, da Lei8.666\/93',
        'Justificativa: SERPRO e integrante da Adm. Poblica, criado para prestar, aos irgaos do Min. Fazenda os servicos que serao contratados.',
        'Objeto: Prestacao de servicos de tratamento de dados, redes de longa dist!ncia e locais, manut encao e desenvolvimento de sistemas de dados, e  servicos especiais, por intermedio de computac ao eletrenica. ',
        'Coordenador-Geral de ProgramaSSY=o e Logstica',
        'ANToNIO MuRCIO DE OLIVEIRA AGUIAR',
        589660719.0
      ],
      [
        '2018-11-28',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Por se tratar de Transferancia de Tecnologia de produto estrategico para o SUS',
        'Objeto: Aquisicao de VACINA HUMANA, MENINGOCOCI CA CONJUGADA GRUPO \'C\',SUSPENSPO INJETuVEL ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        572850000.0
      ],
      [
        '2012-11-16',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: A Abbott Laboratirios do Brasil Ltda possui exclusividade para a producao e comercializacao do medicamento no Brasil.',
        'Objeto: Trata-se da aquisicao de 551.536 sering as de Adalimumabe 40mg. ',
        'Coordenadora-geral de An$?lise Das ContataSSies de Insumos Estrat(c)gicos para Saode - Cgies',
        'MARIANA NOGUEIRA DE RESENDE SOUSA',
        570597084.0
      ],
      [
        '2010-12-16',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Artigo 24, inciso XVI, da    Lei 8.666\/93',
        'Justificativa: Para atender demanda do INSS',
        'Objeto: Contratacao com a Dataprev, com vigenci a de 12 meses, para prestacao de servicos de te cnologia e informacies, em !mbito nacional, par a o INSS. ',
        'Diretor de OrSSamento, FinanSSas e Logstica',
        'GUILHERME FERNANDO SCANDELAI',
        570096528.0
      ],
      [
        '2018-08-15',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Dispensada a licitacao por se tratar de fundacao de apoio PS irgao da administracao poblica direta',
        'Objeto: Aquisicao de VACINA HUMANA, ANTI-HPV (P APILOMA V?RUS), TETRAVALENTE, MONODOSE, SUSPENS PO INJETuVEL ',
        'Coordenador Geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        567420000.0
      ],
      [
        '2018-01-31',
        'MINISTeRIO DO TRABALHO E PREVIDeNCIA SOCIAL',
        'COORDENAcaO GERAL DE REC. LOGiSTICOS - MTPS',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Objeto: Contratacao da Caixa Econemica Federal para servicos de habilitacao e identificacao do s trabalhadores com direito ao Abono Salarial,  participantes do Programa de Integracao Social    PIS; o pagamento do Abono Salarial aos empre gados do Setor Privado com direito ao benefcio ; a apuracao e o controle dos valores, processa mento dos dados, atendimento aos trabalhadores,  bem como a disponibilizacao do acesso PS inform acies cadastrais, inerentes ao Abono Salarial. ',
        'Soad Substituto',
        'HELIO FRANCISCO DE MIRANDA',
        545481975.0
      ],
      [
        '2012-01-31',
        'COMANDO DO EXERCITO',
        'HOSPITAL MILITAR DE AREA DE BRASILIA',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Singularidade do objeto e inviabilidade de competicao.',
        'Objeto: Contratacao de servicos especializados de natureza contnua na area Saode para o atend imento Domiciliar, Ambulatorial e Medico-Hospit alar aos beneficiarios do FUSEx e aos Servidore s Civis do Exercito Brasileiro. ',
        'Ordenador de Despesas do Hmab',
        'PAULO SERGIO IGLESSIAS',
        540600000.0
      ],
      [
        '2017-07-12',
        'INST.NACIONAL DE EST.E PESQUISAS EDUCACIONAIS',
        'MEC\/INEP\/INST.NAC.DE EST.E PESQ.EDUCAC.\/DF',
        'Fundamento Legal: Art. 24o, Inciso XIII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Acirdao 2139\/2014 - TCU',
        'Objeto: Contratacao do Consircio CESGRANRIO\/FGV \/VUNESP para prestacao de servicos especializad os de aplicacao para o Exame Nacional do Ensino  Medio   Enem, conforme condicies e especificac ies contidas no Projeto Basico. ',
        'Diretora de GestY=o e Planejamento',
        'EUNICE DE OLIVEIRA FERREIRA SANTOS',
        525190375.0
      ],
      [
        '2011-12-16',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: A empresa Abbott Laboratirios do Brasil Ltda e fabricante e distribuidora exclusiva em todo territirio nacional.',
        'Objeto: Trata-se da aquisicao de 430.000 sering as-preenchidas do medicamento Adalimumabe 40mg solucao injetavel. ',
        'Coordenadora-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode - Cgies',
        'GISELIA FERREIRA',
        523365900.0
      ],
      [
        '2008-03-06',
        'MINISTERIO DA JUSTICA',
        'SECRETARIA NACIONAL DE SEGURANCA PUBLICA',
        'Fundamento Legal: Artigo 24, inciso VIII, da   Lei 8.666\/93',
        'Justificativa: Conforme memorando no 280\/08\/gab\/mj.',
        'Objeto: Contratacao de instituicao especializa- da para a realizacao da prestacao de servicos tecnicos com vistas a implementacao do PROGRA- MA BOLSA FORMACAO mediante a emissao do cartao PRONASCI e processo de pagamento aos beneficia- rios por meio de transferencia direta de valo- res com vistas a beneficiar 200.000 profissio- nais\/ano. ',
        'Coordenadora Geral de Ensino',
        'JULIANA MARCIA BARROSO',
        511187400.0
      ],
      [
        '2008-03-07',
        'MINISTERIO DA JUSTICA',
        'SECRETARIA NACIONAL DE SEGURANCA PUBLICA',
        'Fundamento Legal: Artigo 24, inciso VIII, da   Lei 8.666\/93',
        'Justificativa: Memorando 280\/08-GAB\/MJ.',
        'Objeto: Constratacao de instituicao especializa da para realizacao da prestacao de servicos tec nicos com vistas a implementacao do Programa Bo lsa Formacao mediante a emissa do cartao PRONAS CI e o processo de pagamento aos beneficiarios por meio de transferencia direta de valore com vistas a beneficiar 200.000 profissionais\/ano. ',
        'Coordenadora-Geral de Ensino',
        'JULIANA MARCIA BARROSO',
        511187400.0
      ],
      [
        '2016-07-15',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: A empresa GILEAD SCIENCES FARMAC 1\/4 UTICA DO BRASIL LTDA detem a exclusividade do produto, em todo territirio nacional.',
        'Objeto: Medicamento Sofosbuvir 400mg. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        510497419.0
      ],
      [
        '2017-11-01',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Dispensada a licitacao por se tratar de uma Transferancia de Tecnologia de produto estrategico para o SUS.',
        'Objeto: Aquisicao de VACINA HUMANA, MENINGOCOCI CA CONJUGADA GRUPO \'C\'. ',
        'Coordenador Geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode - Substituta',
        'ADRIANA RODOVALHO BEZERRA',
        493050000.0
      ],
      [
        '2014-09-08',
        'MINISTERIO DEFESA',
        'DEPARTAMENTO DE ADMINISTRACAO INTERNA',
        'Fundamento Legal: Art. 24o, Inciso VIII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Confere PS TELEBRAS a atribuicao de concessionaria geral para exploracao dos servicos de telecomunicacies.',
        'Objeto: Cessao de direitos de uso futuro, inali enavel, irretratavel, exclusivo e irrestrito da  infraestrutura Satelital da Banda X, pela TELE BRAS ao MD ',
        'Ordenador de Despesas',
        'RUI ALENCAR ANDRADE',
        489360000.0
      ],
      [
        '2018-05-03',
        'MINISTERIO DA INTEGRACAO NACIONAL',
        'SECRETARIA DE INFRA-ESTRUTURA HIDRICA - SIH',
        'Fundamento Legal: Art. 24o, Inciso XI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao de empresa remanescente do RDC Eletrenico N.o 07\/2016, Processo SEI n.o 59008.000891\/2016-42',
        'Objeto: Execucao das obras civis, fornecimento,  instalacao, montagem, testes e comissionamento  das obras complementares do Trecho I   Eixo No rte, do Projeto de Integracao do Rio Sao Franci sco com Bacias Hidrograficas do Nordeste Setent rional   PISF. ',
        'Secretario de Infraestrutura Hdrica - Substituto',
        'MARCUS AURELIUS ARAGAO VERAS',
        485771461.0
      ],
      [
        '2008-12-18',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Artigo 24, inciso XVI, da Lei8.666\/93',
        'Justificativa: Executar servicos de tecnologia e informacao.',
        'Objeto: Prestacao de servicos de Tecnologia e I nformacies. ',
        'Diretor de OrSSamento, FinanSSas e Logstica.',
        'GUILHERME FERNANDO SCANDELAI',
        473821069.0
      ],
      [
        '2016-02-12',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao de insumos estrategicos para a saode com Parceria de Desenvolvimento Produtivo ? PDP.',
        'Objeto: Concentrado de Fator de Coagulacao, fat or VIII Recombinante, PO LIOFILO P\/ INJETuVEL. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        471500000.0
      ],
      [
        '2016-01-15',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Art. 24o, Inciso XVI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Enquadramento no Art. 24 Inciso XVI da Lei 8.666\/93',
        'Objeto: Contratacao da Empresa de Tecnologia da  Informacao da Previdancia Social - DATAPREV, p ara prestacao de servicos especializados em, su porte e manutencao de sistemas em producao, ela boracao, desenvolvimento, implantacao e sustent acao de projetos e sistemas com uso de Tecnolog ia da Informacao, servicos de comunicacao corpo rativa, apuracies e extracies de dados, consult oria, hosting, colocation e microfilmagem. ',
        'Diretor de OrSSamento, FinanSSas e Logstica',
        'LENILSON QUEIROZ DE ARAUJO',
        469831028.0
      ],
      [
        '2009-12-24',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Artigo 24, inciso IV, da Lei 8.666\/93',
        'Justificativa: Trata-se de aquisicao emergencial visto a pandemia da influenza do tipo a H1N1.',
        'Objeto: Aquisicao de 40.000.000 de doses de Vac ina Humana Influenza Tipo A H1N1, vacina para a dministracao por injecao intramuscular - frasco s com no mnimo 10 doses\/frasco. ',
        'Diretor do Depratamento de Logstica',
        'VAGNER DE SOUZA LUCIANO',
        465532000.0
      ],
      [
        '2015-06-05',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Transferancia de tecnologia de produto estrategico para o Sistema thnico de Saode - SUS.',
        'Objeto: Aquisicao de 11.000.000(onze milhies) d e doses de Vacina Humana, Anti-HPV (Papiloma V rus), Tetravalente, Monodose, suspensao injetav el, seringa preenchida. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        465355000.0
      ],
      [
        '2010-12-29',
        'COMANDO DO EXERCITO',
        'ESTADO-MAIOR DO EXERCITO-MEX\/DF',
        'Fundamento Legal: Artigo 24, inciso XXVIII, da Lei 8.666\/93',
        'Justificativa: Fornecimento de bens e servicos que envolvem, alta tecnologia e defesa nacionala serem produzidos ou prestads no pas.',
        'Objeto: Contratacao para aquisicao futura de 21 6 (duzentos e dezesseis) sistemas de armas - ca nhao 30 mm, UT 30BR, para serem integrados PSs v iaturas blindadas de transporte de pessoal, med ia de rodas (VBTP_MR)para atender PSs necessidad es de Organizacies Militares do Exercito Brasil iro. ',
        'Ordenador de Despesas do EME',
        'CARLOS ALBERTO PASSARELA ARANTES- CEL',
        465168096.0
      ],
      [
        '2010-03-30',
        'MINISTERIO DO DESENV. SOCIAL E COMBATE A FOME',
        'SECRETARIA NACIONAL DE RENDA E CIDADANIA',
        'Fundamento Legal: Artigo 25, inciso II, da Lei 8.666\/93',
        'Justificativa: Contratacao do agente operador  do Programa Bolsa Familia - conforme determina o art. 12 da Lei 10.836\/2004.',
        'Objeto: Prestacao de servicos para execucao  o- peracional de acies estabelecidas no contrato e no seu anexo, considerando a operacao do Cadas- tro thnico para Programas Sociais -  Cadonico  e operacao das acies de Transferencia de Renda do Governo Federal sob a Gestao do MDS. ',
        'Secret$?ria Nacional de Renda de Cidadania',
        'LUCIA MARIA MODESTO PEREIRA',
        457000000.0
      ],
      [
        '2018-02-21',
        'COMANDO DA AERONAUTICA',
        'CENTRO DE AQUISICOES ESPECIFICAS',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: >> a onica empresa no Brasil capacitada e certificada pelos Orgaos Oficiais Aeronauticos Brasileiros.',
        'Objeto: Suporte logstico contratado para todos  os modelos de aeronaves H225M (V\/H-36) das For cas Armadas Brasileira. ',
        'Ordenador de Despesas do Gal',
        'MARCELO TENORIO DE CARVALHO',
        451683962.0
      ],
      [
        '2015-01-20',
        'MINISTERIO DA FAZENDA',
        'MF-SRF-SECRETARIA DA RECEITA FEDERAL\/DF',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Inviabilidade de competicao',
        'Objeto: Prestacao de servicos continuados de ar recadacao de receitas federais, por meio do Doc umento de Arrecadacao de Receitas Federais (Dar f), do Documento do Simples Nacional (Das) e da  Guia da Previdancia Social (GPS). ',
        'Coordenador-geral de ProgramaSSY=o e Logstica',
        'NILTON COSTA SIMOES',
        448546375.0
      ],
      [
        '2019-01-22',
        'FUNDACAO OSWALDO CRUZ',
        'INSTITUTO DE TECNOLOGIA EM IMUNOBIOLOGICOS',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O material e o onico que atende PSs necessidades da unidade',
        'Objeto: Importacao de vacina pneumo 10-valente ',
        'Assessora da V.d. de Producao',
        'CARLA FRANCA WOLANSKI DE ALMEIDA',
        446327409.0
      ],
      [
        '2016-12-23',
        'COMANDO DO EXERCITO',
        'COMANDO DA 4 REGIAO MILITAR\/DIV EX',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Por se tratar de profissionais credenciados pela associacao de classe a serem remuneradas pela tabela CBHPM com acresc 15%.',
        'Objeto: Credenciamento de Organizacies Civis de  Saode. ',
        'Ordenador de Despesas',
        'MARCOS MOTA BASTOS',
        439800000.0
      ],
      [
        '2018-03-05',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Dispensada a licitacao por se tratar de uma Transferancia de Tecnologia de produto estrategico para o SUS',
        'Objeto: Aquisicao de CONCENTRADO DE FATOR DE CO AGULA,PO, FATOR VIII RECOMBINANTE, PO LIOFILO P \/ INJETuVEL ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        427905000.0
      ],
      [
        '2011-01-28',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Artigo 25, inciso I, da Lei  8.666\/93',
        'Justificativa: A empresa e fabricante e distribuidora exclusiva em todo o territirio nacional do produto HUMIRA.',
        'Objeto: Aquisicao de 290.000 seringas preenchid as do medicamento Adalimumabe 40 mg - solucao i njetavel. ',
        'Coordenadora Geral de An$?lise das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'GISELIA FERREIRA',
        405710000.0
      ],
      [
        '2008-12-18',
        'SERVICO FEDERAL DE PROCESSAMENTO DE DADOS',
        'SERPRO - SEDE BRASILIA',
        'Fundamento Legal: Artigo 25, Caput, da Lei     8.666\/93',
        'Justificativa: Fornecedor exclusivo.',
        'Objeto: Servicos de Assistencia medico-hospita- lar. ',
        'Diretora',
        'VERA LthCIA DE MORAES',
        402936600.0
      ],
      [
        '2017-03-07',
        'FUNDACAO OSWALDO CRUZ',
        'INSTITUTO DE TECNOLOGIA EM IMUNOBIOLOGICOS',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O material e o onico que atende PSs necessidades da Unidade',
        'Objeto: Importacao de Vacina Pneumo 10-Valente ',
        'Assessora da Vice-diretoria de Gestao e Mercado',
        'CINTIA NUNES CARDOSO LOPES',
        398849173.0
      ],
      [
        '2016-04-25',
        'FUNDACAO OSWALDO CRUZ',
        'INSTITUTO DE TECNOLOGIA EM IMUNOBIOLOGICOS',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O Material requisitado e o onico que em razao das suas caractersticas tecnica atende as necessidade do Departamento',
        'Objeto: Importacao de vacina pneumo 10-valente ',
        'Substituta Eventual do Depad',
        'ANDREA GOOD LIMA COUTO',
        395333410.0
      ],
      [
        '2014-02-26',
        'FUNDACAO OSWALDO CRUZ',
        'INSTITUTO DE TECNOLOGIA EM IMUNOBIOLOGICOS',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O material solicitado e o onico que atende as necessidades da Unidade.',
        'Objeto: Importacao de Vacina Pneumocicica 10 Va lente - Conjugada. ',
        'Substituta Eventual do Depad',
        'ANDREA GOOD LIMA COUTO',
        394683924.0
      ],
      [
        '2015-03-19',
        'FUNDACAO OSWALDO CRUZ',
        'INSTITUTO DE TECNOLOGIA EM IMUNOBIOLOGICOS',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O material solicitado e o onico que atende as necessidades da Unidade.',
        'Objeto: Importacao de Vacina Pneumocicica 10-Va lente. ',
        'Substituta Eventual do Depad',
        'ANDREA GOOD LIMA COUTO',
        394653123.0
      ],
      [
        '2017-02-23',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Trata-se de contratacao de insumos estrategicos para a saode referente ao 4o ano de Parceria de Desenvolvimento Produtivo',
        'Objeto: Aquisicao de Concentrado de Fator de Co agulacao - Fator VIII Recombinante. ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode.',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        394437350.0
      ],
      [
        '2008-11-20',
        'MINISTERIO DO DESENVOLVIMENTO AGRARIO',
        'MINISTERIO DO DESENVOLVIMENTO AGRARIO',
        'Fundamento Legal: Artigo 24, inciso VIII, da   Lei 8.666\/93',
        'Justificativa: necessidade das Secretarias do MDA para operar os programas de governo.',
        'Objeto: Contratacao da Caixa Econemica Federal - CEF para operar como agente financeiro do pro grama de credito fundiario. ',
        'Secret$?rio de Reordenamento Agr$?rio',
        'ADHEMAR LOPES DE ALMEIDA',
        385854007.0
      ],
      [
        '2008-12-01',
        'MINISTERIO DO DESENVOLVIMENTO AGRARIO',
        'MINISTERIO DO DESENVOLVIMENTO AGRARIO',
        'Fundamento Legal: Artigo 24, inciso VIII, da   Lei 8.666\/93',
        'Justificativa: operacionalizacao do Programa Nacional de Credito Fundiario - PNFC',
        'Objeto: Contratacao do Banco do Nordeste do Bra sil S.A., para repasse e gestao de recursos fin anceiros destinados aos Subprojetos de Aquisica o de Terras - SAT e Subprojetos de Investimento s Basicos - SIB, referentes ao Projeto de Credi to Fundiario e Combate PS Pobreza Rural, bem com o autorizar o Banco do Nordeste do Brasil S.A. a administrar os recursos financeiros destinado s PS realizacao do projeto. ',
        'Subsecret$?rio de Reordenamento Agr$?rio',
        'ADHEMAR LOPES DE ALMEIDA',
        385854007.0
      ],
      [
        '2008-12-24',
        'MINISTERIO DO DESENVOLVIMENTO AGRARIO',
        'MINISTERIO DO DESENVOLVIMENTO AGRARIO',
        'Fundamento Legal: Artigo 24, inciso VIII, da   Lei 8.666\/93',
        'Justificativa: Aplicacao de recursos nas atividades-fim do MDA.',
        'Objeto: Celebracao de Contrato que entre si cel ebram a Uniao Federal, por meio do MDA e o Banc o do Brasil S.A., para gestao e aplicacao dos r ecursos financeiros destinados PS concessao de f inanciamento para aquisicao de imiveis rurais d iretamente pelos trabalhadores rurais, referent es aos recursos do Fundo de Terras e da Reforma  Agraria, objeto da Lei Complementar no 93, de 04 de fevereiro de 1998. ',
        'Secret$?rio de Reordenamento Agr$?rio',
        'ADHEMAR LOPES DE ALMEIDA',
        385854007.0
      ],
      [
        '2012-10-05',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 25o, Inciso I da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Wyeth Ind Farm Ltda e fabricante e distribuidora exclusiva em todo territirio nacional do referido medicamento.',
        'Objeto: Aquisicao de 152.388 frascos-ampolas de  Etanercepte 25mg e 704.496 seringas-preenchida s de Etanercepte 50mg. ',
        'Coordenadora-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode - Substituta',
        'MARIANA NOGUEIRA DE RESENDE SOUSA',
        384724032.0
      ],
      [
        '2016-07-12',
        'FUNDO NACIONAL DE DESENVOLVIMENTO DA EDUCACAO',
        'FUNDO FINANC. ESTUDANTE DE ENSINO SUPERIOR',
        'Fundamento Legal: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Art. 25o, Caput da Lei no 8.666 de 21\/06\/1993.',
        'Objeto: Contratacao de agente financeiro  para prestar servicos ao Fundo de Financiamento Estu dantil (FIES), relativos aos contratos de finan ciamento do FIES formalizados apis 14 de janeir o de 2010. ',
        'Diretor',
        'ANTONIO CORREA NETO',
        382000000.0
      ],
      [
        '2017-12-06',
        'FUNDACAO OSWALDO CRUZ',
        'INSTITUTO DE TECNOLOGIA EM IMUNOBIOLOGICOS',
        'Fundamento Legal: Art. 24o, Inciso XXXII da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: O material e o onico que atende as necessidades da Unidade',
        'Objeto: Aquisicao de Vacina Pneumocicica ',
        'Assessor da Vgest',
        'ARMANDO JOSE DE AGUIAR PIRES',
        379030104.0
      ],
      [
        '2016-01-18',
        'MINISTERIO DA SAUDE',
        'DEPARTAMENTO DE LOGISTICA EM SAUDE',
        'Fundamento Legal: Art. 24o, Inciso IV da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Trata-se de Acao Judicial',
        'Objeto: Aquisicao de 14217fra SOLIRIS 300MG ',
        'Coordenador-geral de An$?lise Das ContrataSSies de Insumos Estrat(c)gicos para Saode',
        'EDUARDO SEARA MACHADO POJO DO REGO',
        376573198.0
      ],
      [
        '2009-12-21',
        'COMANDO DO EXERCITO',
        'COMANDO LOGISTICO',
        'Fundamento Legal: Artigo 25, inciso I, da Lei  8.666\/93',
        'Justificativa: Fornecedor exclusivo',
        'Objeto: Reconstrucao\/modernizacao  de 34 (trint a e quatro) helicipteros  AS 356 K-Pantera, da Aviacao do Exercito ',
        'Ordenador de Despesas do Comando Logstico',
        'ROBSON NOVAES HUREN - CEL',
        375803725.0
      ],
      [
        '2004-02-12',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Artigo 24 ,inciso XVI ,da Lei8.666\/93',
        'Justificativa: Atendimento Memo\/397\/CGTI\/INSS\/2003',
        'Objeto: Contratacao de prestacao de servicos - DATAPREV ',
        'Diretor de OrSSamento, FinanSSas e Logstica',
        'JOPO 2NGELO LOURES',
        374221013.0
      ],
      [
        '2011-08-09',
        'INST.NACIONAL DE EST.E PESQUISAS EDUCACIONAIS',
        'MEC\/INEP\/INST.NAC.DE EST.E PESQ.EDUCAC.\/DF',
        'Fundamento Legal: Artigo 24, inciso XIII, da   Lei 8.666\/93',
        'Justificativa: Realizar o Exame Nacional do Ensino Medio.',
        'Objeto: Prestacao de servicos especializados pa ra a aplicacao do Exame Nacional do Ensino Medi o - podendo ocorrer duas ou mais edicies em cad a 12 (doze) meses, conforme condicies e especif icacies contidas no Projeto Basico. ',
        'Ordenador de Despesa',
        'DENIO MENEZES DA SILVA',
        372479758.0
      ],
      [
        '2017-02-02',
        'PRESIDENCIA DA REPUBLICA',
        'SECRETARIA DE PORTOS',
        'Fundamento Legal: Art. 24o, Inciso XI da Lei no 8.666 de 21\/06\/1993.',
        'Justificativa: Contratacao de obra remanescente.',
        'Objeto: Contratacao do Consircio Van Oord\/Boska lis para Elaboracao dos Projetos Basico e Execu tivo de Dragagem e Execucao das Obras de Dragag em por Resultado para Readequacao da Geometria do Canal de Acesso Aquaviario e dos Bercos de A costagem do Complexo Portuario de Santos-SP e d emais servicos e operacies necessarias e sufici entes PS entrega das obras, conforme o Anteproje to de Dragagem e especificacies do Termo de Ref erancia. ',
        'Secret$?rio de Infraestrutura Portu$?ria',
        'DANIEL MACIEL DE MENEZES SILVA',
        369091000.0
      ],
      [
        '2011-06-27',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Artigo 25, Caput, da Lei     8.666\/93',
        'Justificativa: Para atender demanda da Diretoria de Benefcios.',
        'Objeto: Contratacao de instituicao bancaria, cu jo objeto e a prestacao de_servicos de pgto de benefcios administrados pelo INSS, com viganci a de 240 meses, considerando que os valores ser ao repassados do Contratado para o Contratante,  salientando que o valor global e estimado. ',
        'Diretor de OrSSamento, FinanSSas e Logstica',
        'PEDRO AUGUSTO SANGUINETTI FERREIRA',
        368716090.0
      ],
      [
        '2002-06-28',
        'INSTITUTO NACIONAL DO SEGURO SOCIAL',
        'COORDENACAO GERAL DE LICITACOES E CONTRATOS',
        'Fundamento Legal: Artigo 24 , inciso VIII  , daLei 8.666\/93, atualizada.',
        'Justificativa: Atender ao Memorando No 405\/DOFL\/INSS, de 24.06.2002.',
        'Objeto: Contratacao de empresa especializada de servicos de Tecnologia e Informacies. ',
        'Diretor de orSSamento, FinanSSas e Logstica',
        'ROBERTO LUIZ LOPES',
        366012238.0
      ]
    ]
  }
;